name = "honeydew"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PRODUCTION = "false"

[[kv_namespaces]]
binding = "HONEYDEW"
id = "test-kv-id"

[[d1_databases]]
binding = "HONEYDEWSQL"
database_name = "honeydew-test"
database_id = "test-d1-id"
